### ISSUE TITLE
Do not allow participants to change their team name (close to the hunt)

### ISSUE THREAD

**Issue by sam-yeom** [flybye22/puzzlehunt_server#100]
Some teams changed their team names after registration, and this caused some confusion among the staff.

Maybe also add a warning to the participants that they cannot change their team name once the team is created.

**Comment by dlareau** [comment]
This is in direct conflict to #54, what was the confusion?

**Comment by dlareau** [comment]
Teams can only change name before the hunt starts, I could even make that "before the day of the hunt" to stop last minute changes. But with registration time starting to affect room selection, being able to make a team and rename it later is very important. (IMO)

**Comment by sam-yeom** [comment]
In that case, maybe finalize the team names, say, 24 hours before the hunt begins? We started assigning rooms and then some team changed their name in the middle of that process.

**Comment by dlareau** [comment]
Yeah, I can do 24 (or even 48) hours as a limiting factor. I think #97 will also help fix that particular problem a bit as it will integrate room assignment into the server.

**Comment by dlareau** [comment]
Unless you comment otherwise, I'm gonna assume that you also don't want people making new teams after this deadline.

**Comment by dlareau** [comment]
Fixed in 9f9ad3c

**Comment by sam-yeom** [comment]
We want people to be able to make new teams within 48 hours of the hunt, but they should not have the option to request rooms through the website. Is this possible to change before next Thursday (48 hours before our fall hunt)?

**Comment by dlareau** [comment]
Yeah I can do that. Part of the fix was making a quickly checkable boolean for this time window, so now I can just move the if statement around to show the registration box but not the "need_a_room" option. Do you want me to throw in some explanatory text for why the option is gone when it goes away?

**Comment by sam-yeom** [comment]
That would be great. Thanks!

**Comment by dlareau** [comment]
Updated in 5529ad7
