### ISSUE TITLE
Add a confirmation dialog to progress-page puzzle unlocks

### ISSUE THREAD

**Issue by sam-yeom** [flybye22/puzzlehunt_server#101]
It is currently too easy to accidentally unlock a puzzle for a team.

**Comment by dlareau** [comment]
Yeah, I think the lack of a confirmation is a hold-over from the "really old days" when we unlocked puzzles by hand at the start of the hunt. This should be easy to add and makes sense.

**Comment by dlareau** [comment]
Fixed in df88ef9
