### ISSUE TITLE
Disable answer submission after a team solves the puzzle

### ISSUE THREAD

**Issue by alexirpan** [flybye22/puzzlehunt_server#104]
When playing around with the default puzzle template, it seems like you can keep submitting answers after a puzzle is solved. It would be nice to just remove the submission text box once it's solved, to make it extra clear there's no point submitting to that puzzle anymore.

**Comment by dlareau** [comment]
Great idea, don't know why I didn't think of it sooner. I'll include it as part of my summer update.
