### ISSUE TITLE
The allergies/preferences question should just be "allergies" (not preferences)

### ISSUE THREAD

**Issue by TomWildenhain** [flybye22/puzzlehunt_server#105]
We are currently in the interesting situation of not being able to distinguish a person wanting peanuts from one allergic to peanuts.

**Comment by dlareau** [comment]
That is unfortunate. I'll remove the word "preferences" right away. That being said, I think in this particular case it is likely that the person is allergic, haven't heard many people profess their preference for peanuts in a food preference box.

On a side note, after having taken most of the summer as a break from this project, I'm probably going to go on an issue resolving sprint in the next week or two and fix most of the standing issues so their ready for y'alls next hunt.

**Comment by dlareau** [comment]
Fixed in 6e8674b
