### ISSUE TITLE
Can't load solutions to Time Travel Hunt

### ISSUE THREAD

**Issue by TomWildenhain** [flybye22/puzzlehunt_server#106]
The solutions to the two most recent hunts (CS Hunt and Quest) load fine, but those for Time Travel Hunt give a 404 even after downloading them from the hunt management page.  The solution PDFs are not visible when I SSH into the server.

https://puzzlehunt.club.cc.cmu.edu/protected/solutions/901_sol.pdf

Random guess: downloading solutions does not work if the hunt is not set as current.

**Comment by dlareau** [comment]
Your guess was correct. I was filtering the puzzle list from the current hunt's list of puzzles rather than all puzzles. Fixed in a4de7c3.
