### ISSUE TITLE
Add the ability to search users by username

### ISSUE THREAD

**Issue by sam-yeom** [flybye22/puzzlehunt_server#109]
In the "Users" page for the staff, we want to be able to search for users by username.

**Comment by dlareau** [comment]
Added in 4ef2ef5. 
Some notes that may or may not apply to what you are doing:
- You basically never want to change the user object for a person
    - The only real scenario I can think of is if you needed to make a person puzzlehunt staff
    - Basically everything else you would want to change about a user should be editable by that user via https://puzzlehunt.club.cc.cmu.edu/user-profile/ which is accessible by clicking their username in the upper right corner when signed in.
    - If they forgot their password the login page has a link to reset it via email
    - Make sure to never change the email for a CMU login based account and make sure to always delete users/persons in pairs, leaving just one will result in undefined behavior
- If you want the Person object associated with a user the Person search bar searches all the user fields as well (first name, last name, email and username)
