### ISSUE TITLE
Check for unicode and convert to ascii when logging anything

### ISSUE THREAD

**Issue by dlareau** [flybye22/puzzlehunt_server#110]
Maybe just create a wrapper function.

**Comment by sam-yeom** [comment]
The server also does not provide automatic responses to answer submissions that contain Unicode characters. Maybe we should strip all characters from answer submissions except [A-Za-z].

**Comment by dlareau** [comment]
Nah, that is actually an unfortunate side effect of the logging. The line logging the response is before the response so the log line errors and the automatic response never makes it back from the server. Unicode answers should totally work work, it's just the log erroring that makes the response part fail.

**Comment by dlareau** [comment]
There are a lot of things that could be done, but it turns out a large part of this is just some python 2 unicode vs byte string garbage. The next version will just be version 4 and will drop support for python 2, "fixing" this issue (#119).

**Comment by dlareau** [comment]
The project is now on Django 2.2 only and therefore python3 only. This is "solved".
