### ISSUE TITLE
Puzzle solutions not uploading

### ISSUE THREAD

**Issue by TomWildenhain** [flybye22/puzzlehunt_server#112]
After populating the puzzle solution field, the solutions for our most recent hunt (Anomaly Hunt) are not loading, even after the puzzle is downloaded from the management page.  The solution link leads to a 404 instead of the requested PDF.

**Comment by dlareau** [comment]
at some point the "_sol" suffix got dropped from the name the file is saved at causing a mismatch between what was being downloaded and what was being asked for by the webpage. Fixed in 264ee87. I've also gone through and redownloaded the solutions, now with the correct file names.
