### ISSUE TITLE
Make clicking the PNG on a puzzle page take you to a PDF

### ISSUE THREAD

**Issue by dlareau** [flybye22/puzzlehunt_server#113]
It would seem that more links are being included in puzzles as puzzles become more dynamic, and that people are dissapointed when they can't click the link in a PNG. The simple workaround for this is to make clicking the PNG take them to the PDF where they can click the link.

**Comment by sam-yeom** [comment]
Alternatively, is it possible to embed a pdf viewer on the puzzle page?

**Comment by dlareau** [comment]
I have thought about PDF viewers, last time I looked basically everything looked messy. 90% of answers were either "Just link the the pdf as a separate page, modern browsers preview PDFs just fine" or were a paid solution. I can look again as that was like 5 years ago.

**Comment by dlareau** [comment]
Oh, sick, either browsers sucked 5ish years ago or I was just bad at searching, apparently nowadays a simple `<embed>` tag will embed a PDF. I'll look at just integrating that.

**Comment by dlareau** [comment]
Fixed in 5b614c3
