### ISSUE TITLE
Sort the progress page by last solve time

### ISSUE THREAD

**Issue by sam-yeom** [flybye22/puzzlehunt_server#115]
Currently, we can sort by last meta solve time or last (non-meta) puzzle solve time, but our tiebreaker is last solve time without regard to whether a puzzle is a meta. I would like to be able to sort teams by last solve time and make it the default.

Also, it would be great if, on the left where it currently shows the number of puzzles solved, we can instead see the number of metas solved, number of non-meta puzzles solved, and the last solve time.

**Comment by dlareau** [comment]
This all sounds pretty easy. Should be no problem.

**Comment by dlareau** [comment]
Working on this now, just making sure you're edge cases work out how you intend. Is it correct that under the "total last time" system, in an example 10 puzzle hunt (with 1 meta) you would want a team that solved all 9 normal puzzles by 6pm and the meta at 7pm to win over a team that solved 8 normal puzzles by 5pm, the meta at 6pm and the 9th normal puzzle at 8pm?

**Comment by sam-yeom** [comment]
Yes, that is correct.

**Comment by dlareau** [comment]
Added in f76e29a
