### ISSUE TITLE
Add time based unlocking

### ISSUE THREAD

**Issue by dlareau** [flybye22/puzzlehunt_server#117]
Spawned from #111 
Add time based unlocking to the server as an option. This is a place to talk about it's workings.

I think getting the feel of this correct will be tough. I struggle to find example numbers that keep the first place team from unlocking everything after like 4 puzzles but allows for the weaker teams to make any progress. I'd like to see some proposed numbers for how this would shake out, so we can solve some possible issues before they come up.

I think this can be partially mitigated by using both unlocking mechanisms together, but I'm also not exactly sure what that would look like either.

**Comment by dlareau** [comment]
@samuel-yeom I'm soon to start implementing this, would you be able to suggest some sample numbers to see if this is feasible before I get too far?

**Comment by sam-yeom** [comment]
Our consensus was that every non-meta puzzle should be unlocked for every team about halfway through the hunt. To prevent the first-place team from unlocking everything too early, we can unlock on average one puzzle per every puzzle solve. Assuming a 16-puzzle, 8-hour hunt, we could have:
- 3 puzzles unlocked at start
- 1 new puzzle unlocked every 20 minutes
- Every puzzle solve gives 20 minutes of credit

**Comment by dlareau** [comment]
This was finished in commit 3398289. Hoping to make it available on the dev site soon.

As shown below, it is now possible to choose whether a puzzle unlocks with solves, points, either or both. 
<img width="775" alt="Screen Shot 2020-02-13 at 9 14 43 AM" src="https://user-images.githubusercontent.com/2934378/74443530-57bbfd00-4e41-11ea-9c7c-612a546c8237.png">
<img width="774" alt="Screen Shot 2020-02-13 at 8 58 20 AM" src="https://user-images.githubusercontent.com/2934378/74442352-5ab5ee00-4e3f-11ea-88c1-c01996ef7db0.png">
