### ISSUE TITLE
Make the "Hunt Info" page customizable

### ISSUE THREAD

**Issue by sam-yeom** [flybye22/puzzlehunt_server#123]
For obvious reasons, our spring hunt will be 100% online, and we want the FAQs to reflect this fact.

**Comment by dlareau** [comment]
Cool, I was actually curious about that fact, I'll get on this.

**Comment by dlareau** [comment]
Added the ability to edit the informational pages (And even add other information pages) in commit f0e8153. It will go live to the server with the v4.0 deployment.
