### ISSUE TITLE
Password reset bug

### ISSUE THREAD

**Issue by sam-yeom** [flybye22/puzzlehunt_server#126]
![unknown](https://user-images.githubusercontent.com/7460748/79050121-e2c53380-7bf5-11ea-8038-711397a0e350.png)

example.com should be changed to the puzzle hunt website URL

**Comment by dlareau** [comment]
This has been fixed for our site as of this post. I'm leaving the issue open because the code still has a problem and the issue would re-appear on any fresh install.

This issue was introduced as a side effect of the ability to edit info pages.

**Comment by dlareau** [comment]
Fixed for fresh installs in commit 5cb8d6a
