### ISSUE TITLE
Possible bug with hint requests

### ISSUE THREAD

**Issue by sam-yeom** [flybye22/puzzlehunt_server#127]
When a team submits a hint request and they have not previously submitted a hint request for that puzzle, the request and the ensuing response do not show up in "Previous Hint Requests" until the page is refreshed. This behavior is different from what happens in the case where a team has previously submitted a hint request for the puzzle.

Is this difference in behavior intentional?

**Comment by dlareau** [comment]
Nope, that is in fact a bug, thankfully a simple one. The template logic didn't put in the table for the hints if there weren't any hints, so the javascript to add the returned hint to the table failed and the first hint wouldn't be displayed. Fixed in 6b67d9e. (And now live on the server)

**Comment by sam-yeom** [comment]
Now the table shows up when you submit the hint request, but it still says "You have not yet submitted any hint requests for this puzzle" below that. That message should disappear when the table appears.

**Comment by dlareau** [comment]
Ugh, you're totally right. This is what I get for trying to fix bugs while my tests run at work. I'll add some code that removes that line when I get a moment.

**Comment by dlareau** [comment]
Now hopefully actually fixed.
