### ISSUE TITLE
Strip nonalphabetic characters from answer submissions

### ISSUE THREAD

**Issue by sam-yeom** [flybye22/puzzlehunt_server#129]
Some less experienced teams include numbers or special characters in their answer submissions. It would be good to strip nonalphabetic characters to signal to them that they are not a part of the answer. Additionally, when displaying previous answer submissions, we want them to be displayed in all uppercase (to signal that answers are case-insensitive).

**Comment by dlareau** [comment]
Per #57, we already strip spaces, underscores, hyphens, colons, semicolons, plus signs, commas, periods, exclamation points, and question marks from the answer. Just to confirm, the request is now to change from that blacklist to a whitelist of A-Z and 0-9? Regardless of whether we go blacklist or whitelist, something I have just thought of is adding the same set of character validation rules to the client side text box, something that should have been done sooner.

Separately, I agree with the uppercasing.

**Comment by sam-yeom** [comment]
We would go a little further and disallow numbers as well. Also, just to be clear, a-z should be allowed but converted to A-Z.

**Comment by timparenti** [comment]
As someone who participated alongside a first-time puzzler this time, some sort of client-side validation reminding/reinforcing the allowed character set would be very much welcome.

I agree with uppercasing submissions in the "previous guesses" feedback, but perhaps such a pre-feedback sanitization process could be extended further:

- Spaces and hyphens (and maybe apostrophes?) come naturally enough in typing that they can continue to be **_silently_** accepted and **_silently_** stripped from the guess, both as-registered and as-echoed back to the team.
- Continue to auto-strip other common ASCII punctuation on the current blacklist, as well as digits, but not-so-silently (i.e., display a little client-side **_warning_** reminding the user that punctuation isn't necessary and is ignored).
- For more esoteric Unicode stuff that's more clearly out-of-scope, a client side _**error**_ seems appropriate, and the guess should not be submitted.

**Comment by dlareau** [comment]
After playing around with it a bit the following is what felt right when using the input (it is basically a slightly more aggressive version of Tim's suggestion):
- **No matter what, all non a-z characters are stripped on the backend and the post-stripping answer is uppercased and displayed back to the user.**
- Spaces, underscores, and hyphens are accepted user-side (and stripped server-side as noted above), but a reminder warning is displayed after submission that there won't be any spacing characters in answers.
- Any other characters in the answer field will throw a form submission error and the form won't be submitted. The warning notes that answers only contain the characters a-z.

Overall (at least on a sample size of 3 :P) it felt weird when spaces were automatically silently stripped, and it felt weird to accept but then backend strip things like numbers even when a warning was displayed.

Edit: The other thing that was brought up is that is more advantageous to reject the form for pretty much any reason as it spams us less and it doesn't count against the user's ratelimit, saving them any possible issues.
