### ISSUE TITLE
Some quality-of-life improvements

### ISSUE THREAD

**Issue by sam-yeom** [flybye22/puzzlehunt_server#131]
1. In the staff hint display, it would be great if clicking the team or puzzle name in the hint request box filters the hint requests so that it only displays ones for that team/puzzle. Also, once the hint requests are filtered, prominently display that they are filtered and add a button to unfilter so that we don't accidentally miss incoming hint requests.
2. We want a way to display all email addresses for a specific team so that we can copy and paste them to email all members of the team (similar to what we currently have in the email page).
3. In the progress table, freeze the puzzle names and team names so that they are still displayed when scrolling down or to the right.

Thanks!

**Comment by dlareau** [comment]
1) Should be easy enough, and sounds like a good idea.
2) I currently have a "lookup" page idea in the works, keep an eye out for my email to huntstaff that will have a future ideas doc in the next few days.
3) Should be do-able somehow, just have to do some HTML/CS/JS research.

**Comment by dlareau** [comment]
1) Done in 3b25a73eec5d8dd6cb5be949910870e2c420a71a
2) Done in 7db46154a85ad0ed8fa56f37e682fc7165a6ee39
3) Done in f0c83b2b1e24c9b11df0e0dbea2ab6bfbbe904ba
