### ISSUE TITLE
Do not allow special characters in puzzle answers

### ISSUE THREAD

**Issue by sam-yeom** [flybye22/puzzlehunt_server#146]
Currently, when a staff member creates a puzzle, the puzzle answer is allowed to contain special characters. Due to the changes made in #129, this means that a puzzle will never be solved if the "correct" answer contains a non-alphabetic character.

This shouldn't be an issue in most cases because the staff will know not to put any non-alphabetic characters in the correct answer, but it seems like a good idea to completely preclude this possibility in case someone makes a mistake.

**Comment by dlareau** [comment]
This sounds fine, this should be easy to add this afternoon or tomorrow.

**Comment by dlareau** [comment]
Added in f79afbd, will be merged and deployed when #147 and #148 are completed.
