### ISSUE TITLE
Allow solutions to be in HTML pages

### ISSUE THREAD

**Issue by sam-yeom** [flybye22/puzzlehunt_server#147]
Currently, it seems that the solution needs to be uploaded as a pdf. It would be great if we can upload HTML solutions as well.

**Comment by dlareau** [comment]
This can be done, I imagine the interface remains the same but the solution link just takes you to a page instead?

**Comment by sam-yeom** [comment]
Yes.

**Comment by dlareau** [comment]
Should be added in fd313e1 which is now live on production. You'll need to check the new "Solution is webpage" box and use the new "solution resource file" field for html solutions. It should work just like how puzzle resources do. A zip file with an index.html inside.
![Screen Shot 2020-11-03 at 3 53 51 PM](https://user-images.githubusercontent.com/2934378/98039512-ce909000-1dec-11eb-83e0-b59e4121b663.png)

**Comment by sam-yeom** [comment]
I'm posting this request under this issue (rather than creating another issue) because it is a minor extension of this issue.

Can the "Solution is webpage" box be checked by default?

**Comment by dlareau** [comment]
Yep, can do

**Comment by dlareau** [comment]
Done, deployed to dev, deployed to prod tomorrow
