### ISSUE TITLE
Clearing a puzzle file does not actually delete the file from server

### ISSUE THREAD

**Issue by sam-yeom** [flybye22/puzzlehunt_server#148]
When I check the "Clear" box to remove the already uploaded puzzle file (pdf or zip), the file is still accessible from the server. Uploading a new ZIP file should delete all files from previous uploads in order to avoid accidental leakage of information.

**Comment by dlareau** [comment]
Huh..... Thats odd. The clear checkbox is just a builtin function of the admin for a file-field. I just figured it would do exactly what you said it should be doing but I guess not. I'll look into it.

In the meantime if there is anything up there that is actually a problem I can point you towards how to delete the files on the server.

**Comment by dlareau** [comment]
Fixed in b0d40d4, to be deployed along with #146 very shortly.
