### ISSUE TITLE
Object unlocking

### ISSUE THREAD

**Issue by EggyLv999** [flybye22/puzzlehunt_server#15]
Is it possible to unlock objects on each puzzle solve?

**Comment by dlareau** [comment]
What is meant by object? I think this is already a feature.

**Comment by dlareau** [comment]
So I've added them back to the admin interface, they could use a bit better interface and should probably have some indicator variable for whether or not a hunt uses unlockables as to not confuse hunters by having an unused unlockables tab in the hunt.

**Comment by dlareau** [comment]
I'm gonna mark this as done though, if people find it's current implementation unsatisfactory, we can open a more specific new issue.
