### ISSUE TITLE
Check for file extensions during puzzle and solution uploads

### ISSUE THREAD

**Issue by sam-yeom** [flybye22/puzzlehunt_server#150]
Currently, the puzzle edit page says that certain uploaded files must be either a pdf or a zip, but there does not seem to be a check to ensure that this is the case. It would be nice to have this check to avoid accidentally using the wrong upload button.

**Comment by xlrnz** [comment]
I can take a look at this! Where I can find the puzzle edit page? Maybe a simple regex line can solve this :)

**Comment by dlareau** [comment]
The puzzle edit page is automatically generated as part of Django's admin site framework:
https://docs.djangoproject.com/en/2.2/ref/contrib/admin/
Which means most of the page is generated from `huntserver/models.py` and `huntserver/admin.py`
If you did want to take a crack at it, you'd probably want to add a `clean` function to the `Puzzle` class that checks for the proper file extension (raising a validation error if incorrect) similar to the example here: https://docs.djangoproject.com/en/2.2/ref/models/instances/#django.db.models.Model.clean

**Comment by dlareau** [comment]
Done, deployed to dev, deployed to prod tomorrow
