### ISSUE TITLE
Add a way for staff members to claim hint requests that they will answer

### ISSUE THREAD

**Issue by sam-yeom** [flybye22/puzzlehunt_server#152]
For the last hunt, we used a voice channel to coordinate who will answer which hint request. This was not ideal because (1) multiple people can't talk at the same time over this channel, and (2) it is hard to keep track of who is answering which hint request while also writing hints yourself.

I have two ideas for how staff members can claim hint requests.
1. I haven't looked into this too much, but have the server post a message to a Discord channel every time a hint request comes in. Then, the staff can use Discord reactions to claim it.
2. Currently, hint requests have two possible statuses: "Answered" and "Unanswered". We can categorize them into three statuses instead: "Answered", "Claimed", and "Unclaimed". Ideally, claimed hint requests should also say who claimed them.

I think I prefer the second option because it makes it easier to check the status of a hint request. Let me know if you have any other ideas.

**Comment by dlareau** [comment]
This seems easy enough to do, staff members already have to be signed in, so getting an associated user to claim a hint request is easy. The details will be in the exact claiming system. Is the claim controlled by a button or by starting to type in the hint response box? Is the claim indefinite? What happens if someone forgets they claimed something? Go ahead and try to plot out answers to a few of these questions, but I think it will still be possible to put a lot of the framework in place for this even without those answers.

**Comment by sam-yeom** [comment]
I was thinking that the claim would be controlled by a button. I think the button approach is better because it would force the staff to be more deliberate about claiming hints. When a hint is claimed, the staff should see on the request that it is "Claimed by [person] at [time]". Due to a delay in refreshing the hint requests page, it is possible that someone would try to claim a puzzle that is already claimed. In that case, they should not be allowed to claim that puzzle.

I think the ability to filter for claimed puzzles should be able to handle the case where someone forgets they claimed something. If we see that a request has been claimed for a long time without a response, we can follow up with the person who claimed the request. Because that person could be unreachable for some reason, I don't think a claim should always preclude other staff members from answering the request.

So overall, here are my initial thoughts:
1. A request must be claimed before it can be answered. (safeguard against accidentally forgetting to claim)
2. A request can be answered when it is claimed by someone else, but there should be a warning on the response pop-up box that the request has already been claimed. (safeguard against claiming and then not answering, as well as accidentally answering an already claimed request)

**Comment by dlareau** [comment]
Done, deployed to dev, deployed to prod tomorrow
