### ISSUE TITLE
Make use of response regex clear

### ISSUE THREAD

**Issue by EggyLv999** [flybye22/puzzlehunt_server#27]
Right now (unless changes have been made recently), the response regex must be done in lowercase to match answer strings. It should be clear that this is the intended behavior of responses.

**Comment by timparenti** [comment]
The regex should probably just be applied case-insensitively; that way, it can be presented as a straightforward fact to both the hunt staff producing the regex and to the teams submitting answers.

I could submit a PR if it's wanted, but at first glance it seems there's only one place regexes are evaluated, and that
```python
re.match(resp.regex, submission.submission_text.lower())
```
could probably just become
```python
re.match(resp.regex, submission.submission_text, re.IGNORECASE)
```

**Comment by dlareau** [comment]
Thanks @timparenti !
