### ISSUE TITLE
Better support for uploading static files

### ISSUE THREAD

**Issue by EggyLv999** [flybye22/puzzlehunt_server#29]
Right now, there are two types of files that might need to be added beyond puzzle links: global ones (css and ttfs) and puzzle related ones. It would be nice to have an interface or at least some instructions on how to do these things for the sake of future maintainability so we don't always need an SSH master to do this stuff.

**Comment by dlareau** [comment]
Commit 4f7438f adds an HTML editor for the hunt pages and a file uploader for simple hunt specific static content (like fonts or pictures). This issue is now waiting for the documentation to be updated on how to upload more complex static content or global static content.
