### ISSUE TITLE
Custom "Correct" message

### ISSUE THREAD

**Issue by TomWildenhain** [flybye22/puzzlehunt_server#30]
It would be really awesome to be able to present a custom message when a user gets an answer correct.  By default, the message would still just be "Correct!" but on some puzzles, a custom message could be useful.

Also, the ability to style the message with html (specifically, to include links) would be fantastic.  If that is too hard, then just making it put a hyperlink on text starting with http:// would suffice.

Thanks so much!

**Comment by dlareau** [comment]
Mostly already solved by #9 and #10.
#9 implemented custom responses, #10 allowed those responses to be used for correct answers. 

I'll admit though that how to add custom responses is not easy right now, I'll work on getting #25 done, which should make that easier.

I'm closing this for correctness, if you want, you can open a new ticket about the hyperlinking.
