### ISSUE TITLE
Hyperlinks in custom correct messages

### ISSUE THREAD

**Issue by TomWildenhain** [flybye22/puzzlehunt_server#33]
Please add the ability to put links on custom correct messages.  Ideally, both the display text and link would be customizable.  Thank you.

**Comment by dlareau** [comment]
What do you imagine using this for? I want an idea of how the user interface should look/feel.

**Comment by TomWildenhain** [comment]
We may want to link to content like other web pages pages or sound files which might contain stuff for the meta.  Or maybe linking to an unlisted YouTube video, etc.  An example response might be something like: "Congratulations.  Thanks to your efforts we discovered this video."  with "this video" having the link.

**Comment by dlareau** [comment]
That sounds good, I do need an answer to the second part though, how would you expect to interact with this? I think it would just be easiest if there was some way to do it when entering the normal correct answer response, but should there be a hyperlink button? should the response phrase box just support some link syntax (HTML, markdown, custom)? Maybe some other interface I hadn't thought of?

**Comment by TomWildenhain** [comment]
Markdown syntax should be good for links.  No need to implement full markdown support, though, just [text](link) and \[ \(, etc. escape sequences.  Also, marking that that particular field has markdown notation for links might be good so we don't forget.

**Comment by dlareau** [comment]
Responses now support basic markdown format of [ link text ] ( http://www.somelink.com ) Because they are converted to <a> tags, it is important to include the http:// in the link, otherwise it will be relative to the current page and you'll end up with something like 
https://puzzlehunt.club.cc.cmu.edu/puzzle/401/www.somelink.com
