### ISSUE TITLE
Prominent alerts for new messages

### ISSUE THREAD

**Issue by TomWildenhain** [flybye22/puzzlehunt_server#35]
When a team receives a new message, can we have some sort of indicator that there is an unread message?  For example, changing the color of chat button and adding an icon.

**Comment by dlareau** [comment]
Easy: This effect would show up when the user loads a new page or refreshes the current page and there is a message.

Hard: This effect shows up without the user having to load a new page or refresh the page. 

Let me know if "easy" is good enough.

**Comment by TomWildenhain** [comment]
Without reloading would be ideal since teams may spend a lot of time on a given puzzle page.

**Comment by dlareau** [comment]
As it stands (notify without refreshing) this would require ajax on every page, which would likely be too much server load. There are 4 options here.
- have a really slow polling ajax requester on every hunt page, something slow like 1 poll per 2 minutes. This would mean it could take up to 2 minutes for a notification to appear after being sent, but might make the ajax load feasible.
- Incorporate faster polling ajax, but only on some subset of pages like the hunt main page. This would likely also make load reasonable.
- Allow this to be done the easy way, where notifications show up only on page loads or refreshes. This would likely be okay, as teams navigate pages relatively frequently. 
- Not implement this feature at all. If the above 3 options all seem unsatisfactory, then there is nothing to be done for this issue. 

Further input is welcome.

**Comment by TomWildenhain** [comment]
Notifications on refresh is fine.  I see that the ajax could cause a lot of load.

**Comment by dlareau** [comment]
Finally added in 5aecd94. I just added in a message count badge next to the chat link in the navbar. When there are no unread messages, the badge is grey and has a "0". When there are unread messages, the badge is red and has the number of unread messages. The messages are considered "read" as soon as they are fetched once from the server, whether that be in an AJAX request on an open chat page or on a fresh chat page load. 

It is now public on the dev server let me know what you think stylistically.
(If the chat page 404's or the unread number doesn't show up that means you aren't on a team, a separate issue I have to fix)

**Comment by sam-yeom** [comment]
Would it be feasible to implement the first option (poll every 2 minutes) within the next few weeks? Now that our hunt is moving entirely online, it is important that the chat notifications behave in the way people usually expect them to.

**Comment by dlareau** [comment]
Yeah, I can probably get something like this going.

**Comment by dlareau** [comment]
I was looking over the issues and forgot to mention that this got implemented. The main hunt and puzzle pages should now poll every 2 minutes for chat messages.
