### ISSUE TITLE
Adapt titlebar to handle old hunts

### ISSUE THREAD

**Issue by dlareau** [flybye22/puzzlehunt_server#38]
Right now the titlebar will always bring you to the current hunt 
(Clicking on "puzzles" brings you to "/hunt/current")

Fix to incorporate the hunt number into the rendering of the page and allow for relational links
Alternatively, add more menu dropdowns to allow picking old hunt pages manually.

**Comment by EggyLv999** [comment]
I thought that we can pick old hunt pages manually already?

**Comment by dlareau** [comment]
The issue that is specifically being referenced above is that when you are on a previous hunt's page, the titlebar links to "puzzles" and "unlockables" link to the current hunt's puzzles and unlockables.

The solutions referenced are either making it so that the puzzle link always "does the right thing" and links to the puzzles for whatever hunt you are looking at, or that the puzzles link gets replaced with a drop down that lets you jump to the puzzles page from any hunt.
