### ISSUE TITLE
Can't edit puzzle names

### ISSUE THREAD

**Issue by EggyLv999** [flybye22/puzzlehunt_server#45]
:(

**Comment by dlareau** [comment]
The custom template in 0125d83 caused some issues with saving for some reason, it wasn't puzzle names that were actually the issue, but rather something wasn't validating properly on the backend regarding which puzzles unlock other puzzles. 

Everything should work now, but the admin forms for which puzzles get unlocked and custom responses will look uglier for this hunt.  (they now have an extra column all populated with the object type name). 

I'll work in the dev branch on getting a solution that works and looks pretty.

**Comment by dlareau** [comment]
Rather than removing the section of the custom tabular template that shows the redundant info, I have now just hid it. This appears to fix the problem and make everything look nice. Calling this closed.
