### ISSUE TITLE
Need link to local password reset form

### ISSUE THREAD

**Issue by timparenti** [flybye22/puzzlehunt_server#47]
[This line](https://github.com/dlareau/puzzlehunt_server/blob/ca122db2eba5195e1b70300cce53326745e27639/huntserver/templates/login_selection.html#L48) should link to the local password reset form added in 1d9ab3cf8de64e2763bcafd4fbb4abb53481ba13 to satisfy #28.

**Comment by dlareau** [comment]
Good idea to put it there. I mentally had allocated it to the same page as whatever #44 ends up in, but this link should live in as many places as possible.

**Comment by dlareau** [comment]
Fixed in 1c62d90
