### ISSUE TITLE
Announcement performance

### ISSUE THREAD

**Issue by EggyLv999** [flybye22/puzzlehunt_server#48]
Announcements cause chat to lag out at least on staff side.

**Comment by dlareau** [comment]
Can't reproduce on either server, I'm going to leave this open for now.
I'll see if there is anywhere I can optimize the code, but likely I'll just see how this operates next hunt. There is no inherent reason this functionality should lag the system. It is internally the same as sending 1 message to each team manually.

**Comment by dlareau** [comment]
I'm pretty sure that when this happened, it was just a legacy of the server overall being slow. If it really is an issue, this can be re-opened.
