### ISSUE TITLE
Team name restrictions

### ISSUE THREAD

**Issue by dlareau** [flybye22/puzzlehunt_server#49]
Team names should have reasonable restrictions, like not being made of all whitespace characters. Allowing such team names can cause poorly rendered HTML.

**Comment by pitrack** [comment]
can we be allowed emoji team names please? 👍 🙏 🅱️

**Comment by dlareau** [comment]
Posting this here for myself when I get around to this issue.
http://blog.manbolo.com/2014/03/31/using-emojis-in-django-model-fields

**Comment by dlareau** [comment]
The restriction part is done, still need to allow new characters like emoji.

**Comment by pitrack** [comment]
any updates on emoji?

**Comment by dlareau** [comment]
Oh, whoops github closed this automatically because of my commit message, which I why I didn't work on it. I'll add this after the hunt this weekend.

**Comment by dlareau** [comment]
Fixed in 69894bb. Emojis for everybody.
(I also await the impending ticket asking me to remove emojis from certain fields)
