### ISSUE TITLE
ctrl/cmd-s should save hunt template when editing

### ISSUE THREAD

**Issue by dlareau** [flybye22/puzzlehunt_server#53]
Need to catch and submit upon ctrl/cmd-s.

**Comment by dlareau** [comment]
I'm gonna put this one on hold for now, the django version is getting really out of date (#37 ) and the admin interface might need to change during that if django-admin-bootstrap can't be worked around. So I don't want to end up writing code that will soon just get thrown away.

**Comment by TomWildenhain** [comment]
This might be slightly useful but isn't a huge concern.  I always use an external editor for the template and play with it locally first.
