### ISSUE TITLE
Temporarily block a team from submitting

### ISSUE THREAD

**Issue by cameronmontag** [flybye22/puzzlehunt_server#55]
It'd be nice to be able to disable a team's submissions for, say, a minute. In particular, this can help us punish spammers.

**Comment by dlareau** [comment]
Did you have an interface in mind for this? I'm trying to figure out the best place to add this. Maybe the progress page next to the team name?

Do you want their submissions while blocked to explicitly be deleted or is it okay if they just get a "Your submissions have been temporarily disabled" auto-response, and hope they get a clue? 

If we go with deleting, we could still send back a message saying they were blocked, but their answers wouldn't be recorded anywhere, so there would be no record of what they were spamming with, and to them besides the message it would look like their submissions just aren't working. It is the more forceful choice, but I think it has a bit less intuitive interaction for hunters. 

I'm also open to suggestions for how this should work.

**Comment by cameronmontag** [comment]
The progress page would be a good place, and a custom response like "Your submissions have been temporarily disabled due to excessive guessing" would be nice :)

**Comment by EggyLv999** [comment]
Maybe we should just do a rate limit? Like 10 submission/min and you're automatically rate limited.

**Comment by dlareau** [comment]
I can do rate limiting, which honestly sounds like a better solution. 
I need some phrase to show up where they're answer/response would go. My current idea is "Submission rejected due to excessive guessing." Let me know if you have something better.

**Comment by dlareau** [comment]
Implemented ratelimiting in 45153d3 at a rate of 10 submissions per minute per user. Let me know if that should be changed or if the ratelimiting response phrase mentioned above should change.
