### ISSUE TITLE
Disallow non-alphabetical characters in answer submission text box

### ISSUE THREAD

**Issue by cameronmontag** [flybye22/puzzlehunt_server#57]
When a team submits an answer with spaces, we currently respond with "Invalid answer (spaces)" and make them resubmit without. It'd be nice to just not let them type spaces (and other non-letter characters) in the text box in the first place, to avoid this.

**Comment by pitrack** [comment]
another option could be to automatically remove spaces?

**Comment by dlareau** [comment]
The original reasoning for this way of doing it was that a few years ago, all answers were guaranteed to be a single word, so we wanted to send a stronger message that the answer they were submitting was definitely wrong solely on the basis that it had spaces in it. 

It seems that that mentality has changed and that is fine, but I do agree that Patrick's suggestion makes more sense. If you are going to allow multi-word answers, I think the better option is just to strip out the spaces on the server before comparison. 

If you have some reason why you'd want to limit the text box instead I would be interested in hearing it. One reason I could think of is that it would make it easier to switch back to the old way than a change in server logic, but I don't know that that is enough to be worth it.

**Comment by cameronmontag** [comment]
Yeah, I agree with stripping out the spaces. That was actually my original idea, but some people were opposed because it would make indexing ambiguous - I don't actually think that'll be a problem, though.

**Comment by dlareau** [comment]
Despite them submitting with spaces, it will still show up on the puzzles page and on the queue with no spaces. They will basically just be deleted in the request. So indexing for something like a meta shouldn't be an issue.

**Comment by dlareau** [comment]
Fixed in 351abee

**Comment by timparenti** [comment]
Probably should also do hyphens, in addition to spaces and underscores?  Possibly just have a list to strip out without complaint, and a further whitelist e.g., `A-Z` so that a proper complaint can be raised if there's still some emoji in there afterwards or something.

**Comment by dlareau** [comment]
Hyphens aren't a bad idea, the idea is only to get rid of separator characters. If any extraneous non separator characters are included in the answer, it is just a wrong answer. Especially because this is being done automatically for the user. If you want to put an emoji in your answer, great, its not a correct answer and shouldn't automatically be converted into one.

**Comment by timparenti** [comment]
Then possibly throw out periods (as used in abbreviations) and other common punctuation as well.
