### ISSUE TITLE
Automatically generate end statistics. 

### ISSUE THREAD

**Issue by dlareau** [flybye22/puzzlehunt_server#58]
I'm already doing like 5 other feature requests, unless somebody comments telling me not to, I'm going to add a page that automatically generates the "first solve team/time and number solve" chart.

**Comment by pitrack** [comment]
this should be for just on-campus/on-site teams right? maybe there could be an option for all teams, but that's less important

**Comment by dlareau** [comment]
Between f177be8 and 74ac836, there is now a puzzle information table and a submissions after solve table (also known as a jokes table).
