### ISSUE TITLE
Solve count on puzzles

### ISSUE THREAD

**Issue by EggyLv999** [flybye22/puzzlehunt_server#60]
We'd like to have the option for teams to see solve counts on the page of each puzzle.

**Comment by dlareau** [comment]
You just mean like a count of how many teams have solved that puzzle on the puzzle page? You say option, should this be toggle-able in some manner?

**Comment by dlareau** [comment]
@EggyLv999 Bump on questions.

**Comment by EggyLv999** [comment]
Yes, a count of how many teams globally have solved it (not including off campus teams). I'm not 100% on having this for every hunt, but we wanted to try it out next hunt-- this isn't something we will be changing during a hunt, so I don't think you need to add an option for it.

**Comment by dlareau** [comment]
This was like a one liner that was free processing-wise if I included all teams (even off campus) so I did that. If you *really* want to exclude off campus teams, I can do that, but it would add another database lookup on pageload.
