### ISSUE TITLE
Server needs new admin plugin

### ISSUE THREAD

**Issue by dlareau** [flybye22/puzzlehunt_server#62]
The next version to be released (V3.3.0) is currently planning to have the server move from Django 1.8 (which end of life'd in April 2018) to Django 1.11 (which is the current LTS release) for security reasons. The current plugin the server uses for the admin interface (django-admin-bootstrapped) doesn't support Django 1.11, so we have switched to the very similarly named "django-admin-bootstrap". 

This issue exists because the new plugin has a different user interface and I want feedback on it before switching. The new interface is live at [https://dev.puzzlehunt.club.cc.cmu.edu/staff](https://dev.puzzlehunt.club.cc.cmu.edu/staff), go check it out and leave feedback here.
(Note: The dev server doesn't accept university logins, staff have been given a local username and password to use to sign in).

Things you'll note are that the top menu is now a sidebar (which is collapsable) and that the interactions with the django generated forms look different.

Please leave any feedback you have here, including anything as simple as "Looks good" or "I don't like this one menu's look".

**Comment by TomWildenhain** [comment]
I like it!  It looks very modern.  I checked the basic functionality and it looks good.  I didn't immediately notice that the filters were on the left, but I think that's a fine place for them.

**Comment by dlareau** [comment]
Closing this, its happening.
