### ISSUE TITLE
Actually do something about the allergies field

### ISSUE THREAD

**Issue by dlareau** [flybye22/puzzlehunt_server#66]
We've been collecting allergy information since version 1.0.0 and doing pretty much nothing with it. It would probably be good to have a hunt page that listed the allergens for the current hunt participants. Some people manage to put jokes in it, but it still is important to look at.

For example, the current hunt's participants have filled the following into the "allergies" box:
(Empty entries and duplicate entries removed)
ice cream
dairy free
Any good food
Turkey
Tasty
Thai food pls
Vegetarian
deserts
Pizza pepperoni
No Eggs
chipotle
no red meat
no cheese
Alfredo Noodles
chicken
Vegan
Not pizza

The concerning ones are one like "Dairy free", "No Cheese" and "Vegan" that would have issues with the standard pizza order.

**Comment by TomWildenhain** [comment]
Yes, I agree this would be useful.  In the interval, you could stop allergy collection entirely (since we don't look at that field normally and I don't want people to falsely think we know their allergies).

**Comment by dlareau** [comment]
Because allergy information is gathered when you make an account (to avoid having to put it in again every hunt) it disabling it would mean that the a person registering now would have to go add it back in at a later point in time, something most people don't know is an option. 

If you still want it disabled I'll CSS hide the field, but I think most people have probably already registered for this hunt (or at least one would hope so 4 days before the hunt). The best I think can be done at this point is have a nice page ready for next hunt, and for this hunt either take the data above into account, or if you want I can privately send a list of allergies mapped to names/contact info and staff can reach out. (Or do nothing and order pizza again, we have been apparently collecting and throwing away allergy data for 3 years now (oops))

**Comment by TomWildenhain** [comment]
OK, that makes sense.  If you have time, can you send me a CSV/text file of the people who said they have allergies.  I agree that for future hunts, a display page would be useful.
