### ISSUE TITLE
Add option to sort progress page by number of puzzles completed

### ISSUE THREAD

**Issue by TomWildenhain** [flybye22/puzzlehunt_server#69]
It would be nice to be able to sort the progress page when we make the final standings.  It would be best to have two sorting options: one by signup order (the current method) and one by team standing (number of metas solved, number of puzzles solved, last puzzle solve time).  This would require that puzzles have an additional "is meta" field.

**Comment by dlareau** [comment]
This sounds totally do-able. Probably won't be able to do any automatic porting of the "is-meta" attribute to previous hunts, but it doesn't really matter.

**Comment by TomWildenhain** [comment]
Awesome!  Since we might change up the ranking criteria in subsequent hunts, it might be nice to have a "ranking criteria" section for Hunt objects that lets us arbitrarily order the items "Number of Metas", "Number of Puzzles", "Last Solve Time", and "Last Meta Solve Time".
