### ISSUE TITLE
Add ability to release puzzle solutions through the server

### ISSUE THREAD

**Issue by TomWildenhain** [flybye22/puzzlehunt_server#71]
It would be awesome if we could put a dropbox link to the solution PDF for a puzzle.  When the hunt closes and goes into the "past hunts" area of the site, the solutions could be accessible via a "download solutions" link below the "click here for a downloadable PDF" link.

**Comment by dlareau** [comment]
This should be relatively easy as a lot of the code for it already exists for puzzle PDFs.

**Comment by dlareau** [comment]
Solved by a88b587
