### ISSUE TITLE
Ability to view past hunts without logging in

### ISSUE THREAD

**Issue by TomWildenhain** [flybye22/puzzlehunt_server#72]
Is there any particular reason why we need people to log in to view a previous hunt?  This isn't high priority but could be a nice enhancement.

**Comment by dlareau** [comment]
99% of why that doesn't happen right now is lazyness. 

Having a page you always log into looks like this:
```python
@login_required()
def hunt_page(request):
    do_stuff()
```

and a page you sometimes log into looks like this:
```python
def hunt_page(request):
    if (not (request.user.is_authenticated or hunt.is_public)):
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
    do_stuff()
```

but given that it only took me like 3 minutes to write that, I can of course overcome lazyness and apply that logic to the hunt pages.

**Comment by dlareau** [comment]
There are of course some other minor code changes that need to happen to allow answer submission while logged out, but I think those will actually be the easiest since I transitioned to DUMMY accounts for public hunts way back in 6e39053
