### ISSUE TITLE
Fix up mobile compatibility

### ISSUE THREAD

**Issue by dlareau** [flybye22/puzzlehunt_server#73]
Mobile compatibility was once a big deal for this project but as things changed and features got added it fell by the wayside, this issue is just to aggregate and fix all issues with mobile viewing. If you have anything wrong, post it here preferably with either a screenshot OR exact phone resolution. I'll also be posting things here as I find them.

**Comment by TomWildenhain** [comment]
Most pages are mobile compatible with the exception of the hunt page itself, which is compatible only if the hunt template is.  This is more of an issue of template design than something that needs to be changed on the server.  The page I was initially referring to had a template with a large min-width.  Unfortunately, wide pages do make the navbar become very narrow, which is something that might be able to be improved.

![Screenshot_20190427-195321](https://user-images.githubusercontent.com/13002846/56856325-3592d600-6926-11e9-97b2-acc42563adff.png)
