### ISSUE TITLE
On progress page, check to see if the team already solved the puzzle before updating

### ISSUE THREAD

**Issue by sam-yeom** [flybye22/puzzlehunt_server#75]

**Comment by dlareau** [comment]
I'm not sure what is being asked here. If possible, please try to include a description in the future.

**Comment by sam-yeom** [comment]
During the fall hunt, some teams re-submitted the correct answer to a puzzle a few hours after first solving it. This updated the solve time on the progress page. When I reloaded the progress page, the old solve time remained, so this makes me think that the live updates on the progress page do not check whether the puzzle has already been solved.

**Comment by dlareau** [comment]
Ah, I've been so accustomed to feature-request issues it didn't occur to me that you might have been referring to buggy behavior. You are correct that if a team resubmits a the correct answer it should not update the progress page with the new time. This should be pretty easy to fix thankfully.

**Comment by dlareau** [comment]
Fixed in 5c08b4f, to be released in version 3.4.
