### ISSUE TITLE
Ability to iterate through all puzzles (not just unlocked puzzles) when making hunt template

### ISSUE THREAD

**Issue by TomWildenhain** [flybye22/puzzlehunt_server#76]
Sometimes we want our templates to be able to show a "locked" icon to represent each locked puzzle.  Currently, the hunt templates iterate over `puzzle_list`, which only includes the puzzles that are unlocked for that team.  Ideally, there would be a `hunt_puzzle_list` that includes all the puzzles in the hunt with an `unlocked` boolean we can check in the template.  This would also enable us to show the names of locked puzzles (if we wanted).

**Comment by dlareau** [comment]
I'll look at including a purpose made variable for easier use and better caching, but for now you can use
`hunt.puzzle_set.all` in place of hunt_puzzle_list
and 
`puzzle in team.unlocked.all` in place of what will probably end up being puzzle.unlocked
Unless there is some urgent need for this, expect this in the 3.4 release aimed at the end of January.

**Comment by TomWildenhain** [comment]
Cool.  I'll use those commands in the interval.

**Comment by TomWildenhain** [comment]
Using `hunt.puzzle_set.all` resolves the issue so I don't think any other changes are needed.

**Comment by dlareau** [comment]
okay, I'll close this, the only correction I would say is that I've since realized that ```puzzle in puzzles``` (the variable "puzzles" referencing the list of unlocked puzzles naturally passed to the template) is cheaper for the server to compute and should be used instead of ```puzzle in team.unlocked.all```.

**Comment by TomWildenhain** [comment]
Actually I just realized that this does not sort the puzzles properly so I'm now using `hunt.puzzle_set.all|dictsort:"puzzle_number"`.  Is that OK?

**Comment by dlareau** [comment]
Yeah, thats fine, so long as you aren't doing that in like 20 different places in the page.
