### ISSUE TITLE
CS Hunt on February 23rd

### ISSUE THREAD

**Issue by TomWildenhain** [flybye22/puzzlehunt_server#78]
Just wanted to let you know that we are holding an additional hunt this year called CS Hunt on February 23rd.  The hunt is targeted towards CS majors and each puzzle is based on a course in the CS curriculum.  The hunt will be an all-day event running from the 12:00 to 8:00 as usual.

The main update we would like to have by then is the code to deal with the server load problems (fewer AJAX requests on the puzzle pages)

If possible it might be nice to have that additional data field for each puzzle (since we are going to use the course numbers as a subtitle)

**Comment by dlareau** [comment]
Thanks for the heads up, all changes *should* be done by then. You can track progress and expected finish dates on the milestones page: https://github.com/dlareau/puzzlehunt_server/milestones

Closing now, as there is nothing to do here.
