### ISSUE TITLE
Replace hunt asset file system

### ISSUE THREAD

**Issue by dlareau** [flybye22/puzzlehunt_server#79]
When the hunt asset file system was added to address #13 and #29, the thought was that we would be using mostly the same fonts and files across many hunts, so having a rough upload process was fine because we'd do it infrequently. Recent hunts have been knocking it out of the park with production value, but they have been doing so by needing more custom static files per hunt. 

I will admit that the hunt asset file system is clunky and sucks for adding more than like 2 files per hunt, so I totally understand manually placing in static files the past few hunts. What I want to know is: "Is there a better replacement?". 
First, I thnk any solution should stick with the following 3 goals:
- Old hunts are preserved and playable at all times. (This helps the organization)
- The only thing that should need to be backed up is the database, everything else should have a copy in cloud storage or git. (This allows for easy redeployment if needed)
- Files specific to individual hunts should not live in git. (That would quickly balloon the repo size, and git is probably harder than FTP)

Some possible solutions I've thought of and would like some feedback on (@TomWildenhain ? (Also, point other people here if they have comments)). 
- Hunt resource links: hunt static files live in dropbox and just like puzzle and prepuzzle links, can be pulled down and accessed from the template.
- Some sort of fully featured web file manager: Basically make the hunt asset file system easier to use, stuff like the ability to upload folders, drag and drop files in. I'm sure I can find some django plugin that just does this, but it is almost certainly going to be messier overall than resource links.
- Nothing: I will fully admit that maybe any web based solution sucks. What I would want to do then is codify in the documentation where static files go, how to put new ones in (via ftp or something), and set up some sort of backup to the cloud solution for them as part of the server.

**Comment by TomWildenhain** [comment]
Adding static files manually doesn't actually bother me now that I know how to do it, but I can see that it isn't optimal for when other people are doing the template.  I think the best way would be similar to how we do prepuzzles: link to a resources.zip on Dropbox and have a special Django tag to reference the resources.

I think having a backup of the server data would still be good.  Older hunts still use manually placed files and I would hate to lose those puzzles if something happened.  A yearly backup solution would probably be sufficient since new hunts will be less reliant on the backup.  Should we create a new issue for this?

**Comment by dlareau** [comment]
Oh, I already backup the server to my NAS once a year, I just plan everything I do to the degree of "what if I get hit by a truck". If the org wanted to start backing up the server as well, I definitely won't stop you. 

Sounds like the official resolution to this issue is the resources link, which now that I've done it twice already should be fine.

**Comment by dlareau** [comment]
As of 1785d95, it is now possible to add a resource URL to hunts, download the content from the management page, and access it using the ```{% hunt_static %}``` tag. Documentation will be properly included in the 3.4 update. 

The old hunt asset feature is now deprecated, to be removed in v4.0 if that ever happens. 
Between HTML puzzles, prepuzzle features, and this, there should now be no need to add new hunt related static files to the server.
