### ISSUE TITLE
Prepuzzle nav bar should collapse navigation before content starts to wrap

### ISSUE THREAD

**Issue by TomWildenhain** [flybye22/puzzlehunt_server#85]
![serverbug](https://user-images.githubusercontent.com/13002846/52441633-30747680-2aef-11e9-8545-01d3b934eb0c.png)

**Comment by dlareau** [comment]
whoops, the close button isn't the comment button...

I thought I had addressed that, but it could be something I added in the past few versions broke it again.

**Comment by dlareau** [comment]
Actually, what is your window/screen resolution? The problem here is that "Homepage" is showing up, when it should only show up on screens small enough that the navbar has already collapsed by default.

**Comment by TomWildenhain** [comment]
On the prepuzzle page, the homepage is showing up when the width is < 990 px.  The navbar collapses below 770 px.

On other pages (like the homepage) the navbar behaves differently.  Homepage is added below 770 px.

**Comment by dlareau** [comment]
The solution is going to be reorganizing a few stylesheets so that prepuzzle.html gets certain parts of what is currently in info_base.html. For now I've applied a patch to the server that fixes 99.9% of possible widths.

**Comment by dlareau** [comment]
Fixed in 8d62d14.
