### ISSUE TITLE
Minor enhancements to the queue filter

### ISSUE THREAD

**Issue by sam-yeom** [flybye22/puzzlehunt_server#92]
In queue, the team is displayed to the left of the puzzle name, but the drop-down lists for the filter are in the opposite order.

Also, the teams in the drop-down list should be sorted in a case-insensitive way.

**Comment by dlareau** [comment]
Fixed by [22c1a40](/dlareau/puzzlehunt_server/commit/22c1a4068d9b2c9f189e5f5465fbef8367aa2d51)
