### ISSUE TITLE
Minor enhancements to chat

### ISSUE THREAD

**Issue by sam-yeom** [flybye22/puzzlehunt_server#99]
1. Prominently display which team we are currently chatting to. Currently, the button of the selected team is not highlighted, and even if it were, only the first ~10 characters of the team name are displayed. I think the best way to do this is to add an area above the chat window where the team name can be displayed.
2. Add a timestamp to chat messages.

**Comment by dlareau** [comment]
Both sound very do-able, I've never quite loved the way the chat looked, I might attempt to make it more user friendly in general in addition to those two things.

**Comment by dlareau** [comment]
These enhancements have been made as of ceee938
- Current team button turns light blue when chatting with them
- Current team is displayed above the text box
- Timestamps are displayed to the right of each message. They aren't perfect for two line messages but I got really sick of CSS after a while and gave up. If anyone knows how to fix that I'll accept a pull request.
